version: '3.5'
services:
  php-fpm:
    image: php74
    container_name: php74
    build:
      context: ./
      dockerfile: ./Docker/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "9999:9000"
    environment:
      APP_ENV: prod